@startuml
'https://plantuml.com/class-diagram

class Image{
    # BufferedImage bufferedImage
    # Pixel[][] greyscalePixels
    # String imagePath
    + Image(String imagePath)
    + String getImagePath()
    + BufferedImage getBufferedImage()
    + Pixel[][] getGrayscalePixels()
    - void loadImageToBuffer()
    + void save(String pathToSave)
    + void bufferedImageToGrayscalePixels(IRgbToGrayscaleFunc rgbToGrayscaleFunc)
}

class HoledImage extends Image{
    - String maskPath
    - IRgbToGrayscaleFunc rgbToGrayscaleFunc
    - Hole hole
    + HoledImage(String imagePath, String maskPath, int cType, IRgbToGrayscaleFunc rgb2GrayFunc, IWeightFunc wFunc)
    + Hole getHole()
    - void carveOutTheHole()
    - void findHole()
    - void findBoundary()
}

class Hole{
    - Set<Pixel> pixels
    - Set<Pixel> boundary
    - IWeightFunc weightFunc
    - int connectedType
    + Hole(int cType, IWeightFunc weightFunc)
    + Set<Pixel> getPixels()
    + Set<Pixel> getBoundary()
    + void addToPixels(Pixel p)
    + void addToBoundary(Pixel p)
    + IWeightFunc getWeightFunc()
    + int getConnectedType()
    + boolean isHole(Pixel p)
}

interface IWeightFunc{
    + float weight(Pixel p1, Pixel p2)
}

interface IRgbToGrayscaleFunc{
    + float rgbToGrayscale(Color c)
}

class Pixel{
    - int x
    - int y
    - float val
    + Pixel(int y, int x, int val)
    + int getY()
    + int getX()
    + float getVal()
    + void setVal(float val)
}

class HoleFillingCalculator implements IHoleFillingCalculator{
    + {static} void fillHole(HoledImage image)
    - {static} float calcColor(Pixel h, Set<Pixel> B, IWeightFunc w)
}

interface IHoleFillingCalculator{
    + {static} void fillHole(HoledImage image)
    + {static} float calcColor(Pixel h, Set<Pixel> B, IWeightFunc w)
}

class MathCalculator{
    + {static} float euclideanDistance(Pixel p1, Pixel p2)
}

class Consts{
    + {static} final double PIXEL_INTENSITY_VALUE
    + {static} final double HOLE_VALUE
}

'Aggregation
Image "1" o-- "many" Pixel : aggregation >
HoledImage "1" o-- "1" Hole : aggregation >


'Composition
HoledImage "1" *-- "1" IRgbToGrayscaleFunc : composition >
HoledImage "1" *-- "1" IWeightFunc : composition >
Hole "1" *-- "1" IWeightFunc : composition >

@enduml
